name: Triggers Filters Demo

on:
  push:
    branches: [ "main", "release/**" ] # Cualquier rama que empiece con release
    paths:
      - "src/**"    #Solo si cambia algo dentro de src
      - "tests/**"  #Solo si cambia algo dentro de tests

  pull_request:
    branches:
      - main
      - release/**
    paths:
      - "src/**"    #Solo si cambia algo dentro de src
      - "tests/**"  #Solo si cambia algo dentro de tests  

permissions: 
  contents: read

jobs:  
  build-filtrado:    
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v4
      
      - name: Confirmar que el trigger pasó los filtros
        run: |
          echo "Branch: ${{github.ref_name}}"
          echo "Evento: ${{github.event_name}}"
          echo "Commit: ${{github.sha}}"
